const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let state={leads:[],chats:[],docs:[],outbox:[],programs:[],agents:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shortDate=d=>d?new Date(d+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';
async function api(path,opts={}){const r=await fetch(path,opts);const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function showView(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id===name));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));const labels={overview:['OVERVIEW','Good morning, team','Your student journey at a glance. Agents prepare the work; your staff stays in control.'],leads:['STUDENTS & CHATS','Student inbox','One clear profile for every student conversation.'],documents:['DOCUMENT REVIEW','Check documents with care','Flag expiry and name mismatch issues for staff review.'],approvals:['MESSAGE APPROVALS','Follow-ups, with your approval','Review every draft before the office records it as sent.'],programs:['UNIVERSITY LIST','Office-approved programs','Every university answer is grounded in these records.'],agents:['AGENT TEAM','A team that works together','Purpose-built agents with clear limits and staff oversight.']};let a=labels[name];$('#crumb').textContent=a[0];$('#pageTitle').textContent=a[1];$('#pageSub').textContent=a[2];history.replaceState(null,'','#'+name);if(name==='leads')renderLeads();if(name==='programs')renderPrograms();if(name==='documents')renderDocs();if(name==='approvals')renderOutbox()}
$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
async function refreshAll(){try{[state.leads,state.chats,state.docs,state.outbox,state.programs,state.agents]=await Promise.all(['/api/leads','/api/chats','/api/documents','/api/outbox','/api/programs','/api/agent-log'].map(api));renderOverview();renderLeads();renderDocs();renderOutbox();renderPrograms();renderAgents();populateSelectors()}catch(e){console.error(e)}}
function renderOverview(){api('/api/summary').then(s=>{$('#stats').innerHTML=[['Saved students',s.leads,'LIVE LEADS'],['Office programs',s.programs,'3+ COUNTRIES'],['Chats recorded',s.chats,'STAFF VISIBLE'],['Awaiting approval',s.pending,s.pending?'REVIEW':'ALL CLEAR']].map((x,i)=>`<div class="stat"><label>${x[0]}</label><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('');let attention=[];if(s.pending)attention.push(`<div class="att-row"><span class="att-icon">◷</span><div><b>${s.pending} reminder${s.pending===1?'':'s'} waiting for approval</b><small>Read the draft before approving</small></div><button class="textbtn" onclick="showView('approvals')">Review →</button></div>`);let unknown=state.chats.filter(x=>x.role==='staff_queue');if(unknown.length)attention.push(`<div class="att-row"><span class="att-icon">?</span><div><b>${unknown.length} question${unknown.length===1?'':'s'} need counselor review</b><small>Outside the approved university list</small></div><button class="textbtn" onclick="showView('leads')">Open →</button></div>`);if(!attention.length)attention.push(`<div class="att-row"><span class="att-icon">✓</span><div><b>You're all caught up</b><small>New items will appear here</small></div></div>`);$('#attention').innerHTML=attention.join('');$('#attentionPill').textContent=s.pending+(unknown.length);});$('#agentMini').innerHTML=state.agents.slice(0,3).map(a=>`<div class="mini-agent"><span class="agent-icon">✧</span><div><b>${esc(a.agent)}</b><small>${esc(a.does)}</small></div></div>`).join('')}
function renderLeads(){let q=($('#leadSearch')?.value||'').toLowerCase();let all=state.leads.filter(x=>[x.name,x.phone,x.country].join(' ').toLowerCase().includes(q));$('#leadCount').textContent=`${all.length} STUDENTS`;$('#leadRows').innerHTML=all.map(l=>{let age=Math.floor((Date.now()-new Date((l.last_reply||l.created_at).slice(0,10)+'T00:00:00'))/86400000);let cs=state.chats.filter(c=>c.lead_id===l.id).length;return `<tr><td><b>${esc(l.name)}</b><small>${esc(l.phone)}</small></td><td>${esc(l.country||'Not set')}</td><td>${esc(l.marks||'—')} marks · IELTS ${esc(l.ielts||'—')}</td><td>${age<=0?'Today':age+' days ago'}</td><td><span class="pill ${age>=3?'amber':'green'}">${age>=3?'FOLLOW UP':'ACTIVE'}</span></td><td><button class="textbtn" onclick="openConversation(${l.id})">${cs} chat${cs===1?'':'s'} →</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No matching students.</td></tr>';let recent=state.chats.slice(-12).reverse();$('#chatList').innerHTML=recent.map(c=>`<div class="chatitem"><div class="line"><b>${esc(c.name)} · ${c.role==='agent'?'Guide agent':c.role==='staff_queue'?'Needs staff':'Student'}</b><small>${esc(c.created_at.slice(0,16).replace('T',' '))}</small></div><p>${esc(c.body)}</p></div>`).join('')||'<div class="empty">Chats will appear here.</div>'}
function openConversation(id){let cs=state.chats.filter(c=>c.lead_id===id);alert(cs.map(c=>(c.role==='agent'?'AGENT':c.role==='staff_queue'?'STAFF REVIEW':'STUDENT')+': '+c.body).join('\n\n')||'No messages yet.')}
function renderDocs(){let d=state.docs;$('#docRows').innerHTML=d.map(x=>`<tr><td><b>${esc(x.name)}</b><small>${esc(x.phone)}</small></td><td>${esc(x.kind)}<small>${esc(x.filename)}</small></td><td><span class="pill ${x.status==='OK'?'green':'red'}">${esc(x.status)}</span></td><td>${esc(x.reason||'No issue found')}</td><td>${esc(x.created_at.slice(0,16).replace('T',' '))}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No documents reviewed yet.</td></tr>'}
function renderOutbox(){let o=state.outbox;$('#outboxList').innerHTML=o.map(x=>`<div class="outbox-item"><span class="bubble">✉</span><section><h4>${esc(x.name)} · ${esc(x.phone)}</h4><p>${esc(x.body)}</p><small>Created ${esc(x.created_at.slice(0,16).replace('T',' '))} · <b>${esc(x.status.toUpperCase())}</b></small></section>${x.status==='pending approval'?`<button class="btn primary" onclick="approve(${x.id})">Approve & mark sent</button>`:`<span class="pill green">SENT ONCE ✓</span>`}</div>`).join('')||'<div class="card empty">No follow-up drafts yet. Run the reminder agent to create drafts for quiet students.</div>'}
function renderPrograms(){let q=($('#programSearch')?.value||'').toLowerCase(),p=state.programs.filter(x=>[x.university,x.program,x.country].join(' ').toLowerCase().includes(q));$('#programCount').textContent=`${p.length} PROGRAMS`;$('#programRows').innerHTML=p.map(x=>`<tr><td><b>${esc(x.university)}</b><small>${esc(x.program)}</small></td><td>${esc(x.country)}</td><td>${esc(x.fee)}</td><td>${esc(x.deadline)}</td><td>${Number(x.marks).toFixed(x.marks%1?1:0)}%</td><td>${Number(x.ielts).toFixed(1)}</td><td>${esc(x.documents)}</td></tr>`).join('')}
function renderAgents(){$('#agentCards').innerHTML=state.agents.map((a,i)=>`<article class="agent-card"><span class="agent-icon">${['◉','⌕','▤','◷','✓'][i]}</span><h3>${esc(a.agent)}</h3><p>${esc(a.does)}</p></article>`).join('')}
function populateSelectors(){['#docLead'].forEach(sel=>$(sel).innerHTML=state.leads.map(l=>`<option value="${l.id}">${esc(l.name)} · ${esc(l.phone)}</option>`).join(''));$('#askProgram').innerHTML=state.programs.map(p=>`<option value="${p.id}">${esc(p.university)} — ${esc(p.program)}</option>`).join('')}
$('#chatForm').onsubmit=async e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));try{let r=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});$('#chatResult').innerHTML=`<b>${esc(r.lead.name)}</b> saved (lead #${r.lead_id}).<br>${esc(r.answer)}`;await refreshAll()}catch(err){$('#chatResult').textContent=err.message}};
$('#uploadForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);$('#uploadMsg').textContent='Reviewing…';try{let r=await api('/api/documents/upload',{method:'POST',body:f});$('#uploadMsg').textContent=r.status+(r.reason?' — '+r.reason:' — no issue found.');await refreshAll()}catch(err){$('#uploadMsg').textContent=err.message}};
async function runReminders(){try{let r=await api('/api/reminders/run',{method:'POST'});alert(`${r.created} new reminder draft(s) created. They are waiting for staff approval.`);await refreshAll()}catch(e){alert(e.message)}}
async function approve(id){try{let r=await api(`/api/outbox/${id}/approve`,{method:'POST'});alert(r.note);await refreshAll()}catch(e){alert(e.message)}}
async function quickAsk(){let p=state.programs.find(x=>x.id==$('#askProgram').value),field=$('#askField').value;let q=field==='fee'?'fee':field==='deadline'?'deadline':'requirements';$('#quickAnswer').textContent=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Demo question',phone:'03000000001',country:p.country,message:`What is the ${q} for ${p.university} ${p.program}?`})}).then(r=>r.answer).catch(e=>e.message);await refreshAll()}
function todayLabel(){const d=new Date;$('#today').textContent=d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}
function routeHash(){let v=location.hash.slice(1);if(['overview','leads','documents','approvals','programs','agents'].includes(v))showView(v)}
window.showView=showView;window.refreshAll=refreshAll;window.renderLeads=renderLeads;window.renderPrograms=renderPrograms;window.renderDocs=renderDocs;window.renderOutbox=renderOutbox;window.runReminders=runReminders;window.approve=approve;window.quickAsk=quickAsk;window.openConversation=openConversation;
todayLabel();refreshAll().then(routeHash);
